
package com.hp.bsc.testing.jmssender.auth;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.8.redhat-7
 * 2016-08-09T15:58:08.515+02:00
 * Generated source version: 2.6.8.redhat-7
 */

@WebFault(name = "InvalidPassword", targetNamespace = "http://ch/hpbsc/zss/authentication/exc/v3/")
public class InvalidPasswordException extends Exception {
    
    private com.hp.bsc.testing.jmssender.auth.InvalidPassword invalidPassword;

    public InvalidPasswordException() {
        super();
    }
    
    public InvalidPasswordException(String message) {
        super(message);
    }
    
    public InvalidPasswordException(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidPasswordException(String message, com.hp.bsc.testing.jmssender.auth.InvalidPassword invalidPassword) {
        super(message);
        this.invalidPassword = invalidPassword;
    }

    public InvalidPasswordException(String message, com.hp.bsc.testing.jmssender.auth.InvalidPassword invalidPassword, Throwable cause) {
        super(message, cause);
        this.invalidPassword = invalidPassword;
    }

    public com.hp.bsc.testing.jmssender.auth.InvalidPassword getFaultInfo() {
        return this.invalidPassword;
    }
}
