
package com.hp.bsc.testing.jmssender.auth;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.8.redhat-7
 * 2016-08-09T15:58:08.589+02:00
 * Generated source version: 2.6.8.redhat-7
 */

@WebFault(name = "UserNotAuthenticated", targetNamespace = "http://ch/hpbsc/zss/exc/v3")
public class UserNotAuthenticatedException extends Exception {
    
    private com.hp.bsc.testing.jmssender.auth.UserNotAuthenticated userNotAuthenticated;

    public UserNotAuthenticatedException() {
        super();
    }
    
    public UserNotAuthenticatedException(String message) {
        super(message);
    }
    
    public UserNotAuthenticatedException(String message, Throwable cause) {
        super(message, cause);
    }

    public UserNotAuthenticatedException(String message, com.hp.bsc.testing.jmssender.auth.UserNotAuthenticated userNotAuthenticated) {
        super(message);
        this.userNotAuthenticated = userNotAuthenticated;
    }

    public UserNotAuthenticatedException(String message, com.hp.bsc.testing.jmssender.auth.UserNotAuthenticated userNotAuthenticated, Throwable cause) {
        super(message, cause);
        this.userNotAuthenticated = userNotAuthenticated;
    }

    public com.hp.bsc.testing.jmssender.auth.UserNotAuthenticated getFaultInfo() {
        return this.userNotAuthenticated;
    }
}
